hosts:

    # PROD
    prod:
        application: 'tipunursery.nz'
        hostname: 'tipunursery.nz'
#        http_user: 'tipunurs'
        remote_user: 'tipunurs'
        stage: 'prod'
        branch: 'main'
        roles:
            - app
            - db
        deploy_path: '/home/tipunurs/www'
#        identity_file: '~/.ssh/id_rsa'
