hosts:

    # PROD
    prod:
        application: 'tipunursery.nz'
        hostname: '51.161.152.16'
        port: 6666
        http_user: 'olga'
        remote_user: 'olga'
        stage: 'prod'
        branch: 'main'
        roles:
            - app
            - db
        deploy_path: '/var/www/tipunursery.nz'
